name: Generate Website Screencap GIF
on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      save_path:
        required: false
        type: string
        default: "/docs/img/"
      gif_name:
        required: false
        type: string
        default: "screenshot"
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        name: checkout repo
      - name: Website to GIF
        uses: PabloLec/website-to-gif@1.0.4
        with:
          url: ${{ inputs.url }}
          save_path: ${{ inputs.save_path }}
          gif_name: ${{ inputs gif_name }}
      - name: Get current date & time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHHMM
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: "${{inputs.save_path}}*"
          commit-message: "bot: 🤖 Screenshot GIF"
          branch: "screenshot-${{ steps.current-time.outputs.formattedTime }}"
          title: "bot: 🤖 Update Screenshot"
