name: Generate Website Screencap GIF
on:
  workflow_dispatch:

jobs:
  call_workflow:
    env:
    uses: joekarow/workflows/.github/workflows/screenshot.yml@main
    with:
      url: "https://" # Site URL
      # save_path: '/docs/img/' # Path where file is saved, must end with /
      # gif_name: 'screenshot' # file name, no extension
    secrets:
      GH_TOKEN: ${{ GITHUB_TOKEN }}
