name: Sync branch
on:
  push:
    branches:
      - main
jobs:
  call_workflow:
    uses: joekarow/workflows/.github/workflows/sync-branch.yml@main
    with:
      target_branch: develop
    secrets: inherit # requires GH_PAT to be set in repo
