name: Run Linter
on:
  pull_request:
  push:

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Identify package manager
        id: pkgman
        uses: joekarow/workflows/which-package-manager@main
      - name: Setup node env
        if: ${{ success() }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        if: ${{ success() }}
        uses: jaid/action-npm-install@v1.2.1
      # - name: Prettier
      #   uses: creyD/prettier_action@v4.2
      #   with:
      #     prettier_options: --ignore-unknown
      #     only_changed: true
      - name: Run lint step
        if: ${{ success() }}
        run: ${{ steps.pkgman.outputs.package_manager}} run lint
