name: Sync branch
on:
  workflow_call:
    inputs:
      target_branch:
        type: string
        required: true
        default: develop
    secrets:
      GH_PAT:
        required: true
jobs:
  sync-branch:
    name: Update ${{inputs.target_branch}} branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: ${{ inputs.target_branch }}
          token: ${{ secrets.GH_PAT }}
          force: false
